server:
  port: 8080

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/camundaworkflow
    username: postgres
    password: admin
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/camundaworkflow
      username: postgres
      password: admin
      driver-class-name: org.postgresql.Driver
      pool-name: HikariCP
      idle-timeout: 3000
      minimum-idle: 10
      maximum-pool-size: 20
      connection-timeout: 2000
      connection-test-query: select 1
      transaction-isolation: TRANSACTION_READ_COMMITTED
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      uri: mongodb://localMongo:secret@localhost:27017/FlowDemo?authSource=admin&readPreference=primary&directConnection=true&ssl=false

camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
    database:
      schema-update: true
    filter:
      create: All
    authorization:
      enabled: true
    history-level: full
    auto-deployment-enabled: true
    job-execution:
      enabled: true